### ISSUE TITLE
Headless browser throws TypeError in applyBestCandidate

### ISSUE THREAD

**Issue by dr-nick** [scottjehl/picturefill#259]
Using the https://github.com/assaf/zombie headless browser for functional testing, I get an error from picturefill:

     TypeError: Cannot read property 'url' of undefined
      at Object.pf.applyBestCandidate (<anonymous>:400:49)
      at picturefill (<anonymous>:583:16)
      at runPicturefill (<anonymous>:599:5)
      at <anonymous>:624:3
      at <anonymous>:641:4

processing the following markup (accessibility attributes removed):

    <picture>
        <source media="(min-width: 43.75em)" sizes="136w" srcset="/files/images/logo-regular.png 136w, /files/images/logo-2x.png 272w">
        <source sizes="5.647058824vw" srcset="/files/images/logo-regular.png 136w, /files/images/logo-small.png 94w">
        <img src="/files/images/logo-small.png">
    </picture>

It appears that there are no `candidates` available in this context, which causes the substitution to fail. Works fine in the real browsers I've tried. Presumably zombie is missing some requisite DOM support, but I guess this could equally befall another, off-mainstream browser. Simplest fix is to guard the function:

    pf.applyBestCandidate = function( candidates, picImg ) {
      if ( !candidates.length ) {
        return;
      }
      ...

**Comment by mike-engel** [comment]
Sorry it's been a while @dr-nick, but has this been fixed as of 2.3.1 for you?

**Comment by dr-nick** [comment]
Nothing's changed in the markup of `applyBestCandidate()` in 2.3.1 to guard for null `candidates`. I've checked out my codebase from back then and it's still throwing the same with that dist release.

If you don't think it's safe to add the guard that I proposed in the initial report, then you may as well close this as an edge case. Zombie is many releases on from here, so I doubt it'd be a problem for anyone coming to use this afresh.

**Comment by mike-engel** [comment]
@aFarkas @wilto I don't see a problem with this, as it could also catch a rare edge case. Thoughts of getting this into 2.3 and 3.0?

**Comment by aFarkas** [comment]
I'm not so sure. A set without any candidate is not a set. I think the problem is caused here because we don't use the ``src`` as a fallback set, if no ``srcset`` was provided. In case this is true, it should be fixed in version 3.0. 

@dr-nick 
Would you be so great to re-test your old project with this [picture fill version](https://github.com/scottjehl/picturefill/blob/afarkas-pf3-proposal/dist/picturefill.js)

**Comment by dr-nick** [comment]
v3.0.0-alpha1 - 2015-06-09 works fine with old zombie codebase, as well as with current production code, so no need for change there.

Your call entirely whether you want to guard the edge case in 2.x as it's otherwise unhandled, or just leave it to obsolescence :)

**Comment by Wilto** [comment]
Into 3.0 it goes. Thanks for all the help, @dr-nick
